image: acastellano/cirunnerbionic

stages:
    - test

unit_tests::
    stage: test
    before_script:
        - export JOBID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        - /bin/echo "ciinprogress 1" | /usr/bin/curl --data-binary @- $IRIS_PERL_CI_URL/instance/$JOBID
        - apt-get update -qq && apt-get install -y gcc make libexpat1 libexpat1-dev libxml2-dev zlib1g-dev cpanminus  libnet-ssleay-perl
    script:
        - perl --version
        - cpanm --quiet --installdeps --notest .
        - perl Makefile.PL && make &&  make test
    after_script:
        - /bin/echo "ciinprogress 0" | /usr/bin/curl --data-binary @- $IRIS_PERL_CI_URL/instance/$JOBID

