image: acastellano/cirunnerbionic

stages:
    - test

unit_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make libexpat1 libexpat1-dev libxml2-dev zlib1g-dev cpanminus  libnet-ssleay-perl
    script:
        - perl --version
        - cpanm --quiet --installdeps --notest .
        - perl Makefile.PL && make &&  make test

unit_tests_using_ubuntu_packages:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make libexpat1 libexpat1-dev libxml2-dev zlib1g-dev cpanminus  libnet-ssleay-perl wget
        - wget -O - http://repo.daedalus-project.io/repo.daedalus-project.io.gpg-key.pub | apt-key add -
        - apt-get update -qq
        - echo "deb [ arch=amd64  ] http://repo.daedalus-project.io/ any daedalus" > /etc/apt/sources.list.d/daedalus-project.list
        - apt-get update -qq
        - apt-get install -y libmoose-perl libmoosex-nonmoose-perl libmoosex-strictconstructor-perl libclass-factory-perl libxml-parser-perl libstring-random-perl libemail-valid-perl libemail-stuffer-perl libmail-transport-perl libdata-validate-domain-perl libmail-transport-perl libemail-sender-transport-smtps-perl libmodule-pluginfinder-perl
    script:
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL && make &&  make test
