image: acastellano/cirunnerbionic

stages:
    - test

unit_tests::
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make libexpat1 libexpat1-dev libxml2-dev zlib1g-dev cpanminus  libnet-ssleay-perl
    script:
        - perl --version
        - cpanm --quiet --installdeps --notest .
        - perl Makefile.PL && make &&  make test
